### ISSUE TITLE
Level Loading Issues (Sponza and Terrain) with Latest Commit 2d06ccf

### ISSUE THREAD

**Issue by Mebourner** [steaklive/EveryRay-Rendering-Engine#46]
Just an FYI, came across your engine and with a fresh git clone it built right out of the box. One issue is commit 2d06ccffedf44fcead3b39978e3bbdaee66f1c9f, the Sponza and Terrain scenes don't load properly. Sponza stays on the test scene and Terrain loads two trees. I'll be digging into seeing if I can help debug what's going on, but just wanted to give you a heads up.

<img width="1433" alt="EveryRay Level Loading Issues" src="https://user-images.githubusercontent.com/7004718/157178108-e291f1bf-a4d0-4f8b-a3bb-30338aca797f.png">

**Comment by steaklive** [comment]
@Mebourner hi! Sponza and Terrain scenes are removed and currently do not exist in the repo. This is due to the refactoring of the scene management (now you have only one generic DemoLevel instance that can load .json scene files from content/levels). Atm there are only testScene and testScene_simple that work and load correctly. I also made empty sponzaScene and terrainScene folders in which i will put correct scenes once the systems (like terrain) will be refactored. Btw, testScene has a sponza model in it (however, i will be moving it out into a separate sponzaScene).

As for the terrain, it is very broken atm, because it was coded directly into the deprecated TerrainDemo.cpp. I am planning to refactor that and move everything terrain-related into a separate system (there is Terrain.cpp already which has a lot), so that it can be loaded into any level (in DemoLevel.cpp like other systems). I am closing this issue and opening a new one about the terrain. Never thought anyone would even check this project to be honest :)

**Comment by steaklive** [comment]
@Mebourner i also updated readme :)
